[package]
name = "appname"
version = "0.1.0"
authors = ["DavidOConnor <david.alan.oconnor@gmail.com>"]
edition = "2018"


[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "^0.2.28"
rebar = "^0.1.0"
